### ISSUE TITLE
Enable strict mode

### ISSUE THREAD

**Issue by dfcreative** [Floby/node-stream-sink#2]
Hi @Floby!

Using this project by [audio-through](https://github.com/audiojs/audio-through), and turns out travis gets the error:
```bash
let _resolve, _reject
  ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

Could you please enable strict mode by default? Appreciate!

**Comment by Floby** [comment]
Hello, I published version 2.0.1 which uses strict mode
